import = ["~/.config/alacritty/themes/themes/github_dark_colorblind.toml"]

[[keyboard.bindings]]
key = "Space"
mods = "Control"
action = "ToggleViMode"

[font]
size = 18.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 1
y = 1
[selection]
save_to_clipboard = true
[scrolling]
history = 5000

[window]

[window.padding]
x = 7
y = 7
